
open Common;;
open Common2;;
open Ast_php;;
module Ast = Ast_php;;

let dummy x = "...";;

let sexp_of_string_wrap = dummy;;
let sexp_of_xhp_tag_wrap = dummy;;
let sexp_of_tok = dummy;;
let sexp_of_qualified_ident = dummy;;
let sexp_of_type_args_option = dummy;;
let sexp_of_hint_type_comma_list_paren = dummy;;

let sexp_of__A_tok_T__P_hint_type_comma_list_dots_paren_P__T__A_tok_T_hint_type_A__option_A__paren x = 
  "very long anonymous type";;

let sexp_of_class_name = dummy;;
let sexp_of_Scope_php_phpscope_ref = dummy;;
let sexp_of_argument_comma_list_paren = dummy;;
let sexp_of_class_name_reference = dummy;;
let sexp_of_expr_option_bracket = dummy;;
let sexp_of_expr_brace = dummy;;
let sexp_of_expr_paren = dummy;;
let sexp_of_scalar = dummy;;
let sexp_of_binaryOp_wrap = dummy;;
let sexp_of_unaryOp_wrap = dummy;;
let sexp_of_lvalue = dummy;;
let sexp_of_assignOp_wrap = dummy;;
let sexp_of_rw_variable = dummy;;
let sexp_of_fixOp_wrap = dummy;;
let sexp_of_expr_option = dummy;;
let sexp_of_list_assign_comma_list_paren = dummy;;
let sexp_of_array_pair_comma_list_paren = dummy;;
let sexp_of_array_pair_comma_list_bracket = dummy;;
let sexp_of_array_pair_comma_list_brace = dummy;;
let sexp_of_argument_comma_list_paren_option = dummy;;
let sexp_of_castOp_wrap = dummy;;
let sexp_of_lambda_def = dummy;;
let sexp_of__A_expr_option_paren_A__option = dummy;;
let sexp_of_encaps_list = dummy;;
let sexp_of_lvalue_paren = dummy;;
let sexp_of_lvalue_comma_list_paren = dummy;;
let sexp_of_xhp_html = dummy;;
let sexp_of_constant = dummy;;
let sexp_of_cpp_directive_wrap = dummy;;
let sexp_of_class_stmt_list = dummy;;
let sexp_of_arithOp = dummy;;
let sexp_of_logicalOp = dummy;;
let sexp_of_xhp_attribute_list = dummy;;
let sexp_of_xhp_body_list = dummy;;
let sexp_of_xhp_tag_option_wrap = dummy;;
let sexp_of_w_variable = dummy;;
let sexp_of_stmt_and_def_list_brace = dummy;;
let sexp_of_if_elseif_list = dummy;;
let sexp_of_if_else_option = dummy;;
let sexp_of_stmt_and_def_list = dummy;;
let sexp_of_new_elseif_list = dummy;;
let sexp_of_new_else_option = dummy;;
let sexp_of_colon_stmt = dummy;;
let sexp_of_for_expr = dummy;;
let sexp_of_switch_case_list = dummy;;
let sexp_of_foreach_var_either = dummy;;
let sexp_of_foreach_arrow_option = dummy;;
let sexp_of_catch = dummy;;
let sexp_of_catch_list = dummy;;
let sexp_of_expr_comma_list = dummy;;
let sexp_of_global_var_comma_list = dummy;;
let sexp_of_static_var_comma_list = dummy;;
let sexp_of_use_filename = dummy;;
let sexp_of_declare_comma_list_paren = dummy;;
let sexp_of__A_tok_T_expr_A__option = dummy;;
let sexp_of_func_def = dummy;;
let sexp_of_class_def = dummy;;
let sexp_of_tok_option = dummy;;
let sexp_of_case_list = dummy;;
let sexp_of_string_wrap_paren = dummy;;
let sexp_of_class_constant_comma_list = dummy;;
let sexp_of_class_var_modifier = dummy;;
let sexp_of_hint_type_option = dummy;;
let sexp_of_class_variable_comma_list = dummy;;
let sexp_of_method_def = dummy;;
let sexp_of_xhp_decl = dummy;;
let sexp_of_class_name_comma_list = dummy;;
let sexp_of__A_tok_M_trait_rule_list_brace_A__Common_either = dummy;;
let sexp_of_modifier_wrap = dummy;;
let sexp_of_xhp_attribute_decl_comma_list = dummy;;
let sexp_of_xhp_children_decl = dummy;;
let sexp_of_xhp_category_decl_comma_list = dummy;;
let sexp_of_xhp_attribute_type = dummy;;
let sexp_of_xhp_value_affect_option = dummy;;
let sexp_of_constant_comma_list_brace = dummy;;
let sexp_of_xhp_children_decl_paren = dummy;;
let sexp_of__A_ident_M_name_T_tok_T_ident_A__Common_either = dummy;;
let sexp_of_ident_option = dummy;;
let sexp_of_static_scalar_comma_list_paren = dummy;;
let sexp_of_constant_def = dummy;;
let sexp_of_type_def = dummy;;
let sexp_of_qualified_ident_option = dummy;;
let sexp_of_toplevel_list_brace = dummy;;
let sexp_of_tok_list = dummy;;
let sexp_of_modifier = dummy;;
let sexp_of_argument_comma_list = dummy;;
let sexp_of_parameter = dummy;;
let sexp_of_parameter_comma_list_dots_paren = dummy;;
let sexp_of__A_tok_T_hint_type_A__option = dummy;;
let sexp_of_type_params_option = dummy;;
let sexp_of_attributes_option = dummy;;
let sexp_of_static_scalar_affect_option = dummy;;
let sexp_of_modifier_wrap_option = dummy;;
let sexp_of_tok_T_tok_T_tok = dummy;;
let sexp_of_class_stmt_list_brace = dummy;;
let sexp_of_interface_option = dummy;;
let sexp_of_extend_option = dummy;;

(**)
